### ISSUE TITLE
홈 API 연결

### ISSUE THREAD

**Issue by syhwang1231** [flower-project-2024/WHOA_iOS#23]
## 💡 요약
* 홈 탭 API 연결 (저렴한 꽃, 오늘의 꽃 조회)
* 꽃 검색 API 연결 (전체 꽃 리스트 조회)
* 꽃 상세 API 연결

## ✅ 체크포인트
* 꽃 상세 페이지 컬러칩 부분, 바텀시트 수정 → 데이터에 맞게 수정 필요
* 오늘의 꽃 조회 - 날짜 탐지해서 매일 변할 수 있도록 해야 함
* 저렴한 꽃 - 꽃말 부분 파싱 필요

## 💻 Task
- [x] 저렴한 꽃 조회 API 연결
- [x] 오늘의 꽃 조회 API 연결 (오늘 날짜로)
- [x] 꽃 검색 API 연결 및 필터링 기능 확인
- [x] 꽃 상세 API 연결
- [x] 꽃 상세 > 꽃말에 스크롤뷰 추가
- [ ] 꽃 상세 → 커스터마이징 이동
- [x] 홈 화면에 스크롤뷰 추가
