### ISSUE TITLE
1차 테스트 이슈 해결

### ISSUE THREAD

**Issue by syhwang1231** [flower-project-2024/WHOA_iOS#38]
## 💡 요약
- 1차 테스트 이후 확인된 이슈 해결

## ✅ 체크포인트
- 탭바 se 대응을 위해 높이 지정

## 💻 Task
- [x] 이미지 저장 팝업 '확인'버튼 작동 확인
- [x] 홈 > 로고와 검색 바 사이 간격 조정
- [ ] 저렴한 꽃 랭킹 5위까지
- [x] 마이페이지 > 저장된 요구서가 없을 때의 화면 필요
- [x] 마이페이지 > ui 위치 수정 필요
- [x] 마이 페이지 > 요구서의 이미지 백그라운드 컬러 삭제
- [x] 탭바 > 높이 지정 (se)
- [x] 꽃 상세 > '이 꽃으로 꾸미기' 버튼 삭제
